### ISSUE TITLE
link to commit when announcing a commit

### ISSUE THREAD

**Issue by HarHarLinks** [KrazyKirby99999/matrix-commit#1]
![image](https://user-images.githubusercontent.com/2803622/146691644-bfbe48fc-6583-4dad-a408-6887790b9437.png)

there is all kinds of info, perhaps it's even a little too verbose, but imo the most useful would be a link straight to the respective commit, which is missing

**Comment by KrazyKirby99999** [comment]
![image](https://user-images.githubusercontent.com/69373044/146852918-264928fe-eba3-4e9e-978d-35450b1fd178.png)

Please close if resolved.
